*&---------------------------------------------------------------------*
*& Include          ZMMR046_F2
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form F_DISPLAY_RPT
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM F_DISPLAY_RPT.

  DATA: LC_MSG TYPE REF TO CX_SALV_MSG.

  TRY.
      CL_SALV_TABLE=>FACTORY(
        IMPORTING
          R_SALV_TABLE = GT_TABLE_ALV
        CHANGING
          T_TABLE      = GT_TABLE ).

    CATCH CX_SALV_MSG INTO LC_MSG.
  ENDTRY.

  GO_FUNCTIONS = GT_TABLE_ALV->GET_FUNCTIONS( ).
  GO_FUNCTIONS->SET_ALL( ABAP_TRUE ).

  GT_TABLE_ALV->SET_SCREEN_STATUS(
    PFSTATUS      = 'ZMMR046_ST'
    REPORT        = SY-REPID
    SET_FUNCTIONS = GT_TABLE_ALV->C_FUNCTIONS_ALL ).

  GO_DSP_SET = GT_TABLE_ALV->GET_DISPLAY_SETTINGS( ).

*--- Zebrado (Striped Pattern)
  CALL METHOD GO_DSP_SET->SET_STRIPED_PATTERN
    EXPORTING
      VALUE = 'X'.

  GO_DSP_SET->SET_LIST_HEADER( 'Reporte carga de SOLPED' ).

* CREATE OBJECT GO_HEADER.

**--- Sociedad
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 1 COLUMN = 1 ).
*  GO_H_LABEL->SET_TEXT( 'Sociedad:' ).
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 1 COLUMN = 2 ).
*  GO_H_LABEL->SET_TEXT( S_BUKRS-LOW ).
*
**--- Centro
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 2 COLUMN = 1 ).
*  GO_H_LABEL->SET_TEXT( 'Centro:' ).
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 2 COLUMN = 2 ).
*  GO_H_LABEL->SET_TEXT( S_WERKS-LOW ).
*
**--- Ejercicio
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 3 COLUMN = 1 ).
*  GO_H_LABEL->SET_TEXT( 'Ejercicio:' ).
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 3 COLUMN = 2 ).
*  GO_H_LABEL->SET_TEXT( S_GJAHR-LOW ).
*
**--- Periodo
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 4 COLUMN = 1 ).
*  GO_H_LABEL->SET_TEXT( 'Período:' ).
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 4 COLUMN = 2 ).
*  GO_H_LABEL->SET_TEXT( S_POPER-LOW ).
*
*  GT_TABLE_ALV->SET_TOP_OF_LIST( GO_HEADER ).
*  GT_TABLE_ALV->SET_TOP_OF_LIST_PRINT( GO_HEADER ).

  GO_SELECTIONS = GT_TABLE_ALV->GET_SELECTIONS( ).
  GO_SELECTIONS->SET_SELECTION_MODE(
    IF_SALV_C_SELECTION_MODE=>ROW_COLUMN ).

  GO_COLUMNS = GT_TABLE_ALV->GET_COLUMNS( ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'BANFN' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
* GO_COLUMNS->SET_OPTIMIZE( 'X' ).
* GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'KATYP' POSITION = '1' ).
* GO_COLUMN->SET_VISIBLE( ABAP_FALSE ).
* GO_COLUMN->SET_SHORT_TEXT( 'Tp.Ct' ).
* GO_COLUMN->SET_MEDIUM_TEXT( '' ).
* GO_COLUMN->SET_LONG_TEXT( '' ).
* GO_COLUMN->SET_CELL_TYPE( 1 ).
* GO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>CHECKBOX_HOTSPOT ).
  GO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>HOTSPOT ).

***--- columnas totales
***--- AA real
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AA' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_AC plan
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_AC' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC real
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG plan
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- versus
***--- AC_AA_IMP
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_AA_IMP' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_AA_PRC
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_AA_PRC' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_PP_IMP
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_PP_IMP' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_PP_PRC
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_PP_PRC' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG_PP_AC_IMP
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG_PP_AC_IMP' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG_PP_AC_PRC
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG_PP_AC_PRC' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 5.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- acumulados
***--- AA_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AA_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_AC_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_AC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 7.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- Versus acumulados
***--- AC_AA_IMP_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_AA_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_AA_PRC_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_AA_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_PP_IMP_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_PP_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- AC_PP_PRC_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'AC_PP_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG_PP_AC_IMP_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG_PP_AC_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- PP_SG_PP_AC_PRC_ACUM
**  TRY.
**      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'PP_SG_PP_AC_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND .
**  ENDTRY.
**  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
*** GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = '' POSITION = '' ).
*** GO_COLUMN->SET_SHORT_TEXT( '' ).
*** GO_COLUMN->SET_MEDIUM_TEXT( '' ).
*** GO_COLUMN->SET_LONG_TEXT( '' ).
**  GS_COLOR-COL = 1.
**  GS_COLOR-INT = 0.
**  GS_COLOR-INV = 0.
**  GO_COLUMN->SET_COLOR( GS_COLOR ).
**
***--- Para ordernar por el campo KATYP y indicar un subtotal
**  G_SORT = GT_TABLE_ALV->GET_SORTS( ).
**  TRY.
**      G_SORT->ADD_SORT( COLUMNNAME = 'KATYP' SUBTOTAL = ABAP_TRUE ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_EXISTING CX_SALV_DATA_ERROR.
**  ENDTRY.
**
***--- Para que funcione los totales
**  GO_AGG = GT_TABLE_ALV->GET_AGGREGATIONS( ).
**
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AA' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_AC' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_AA_IMP' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_AA_PRC' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_PP_IMP' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_PP_PRC' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG_PP_AC_IMP' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG_PP_AC_PRC' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AA_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_AC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_AA_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_AA_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_PP_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'AC_PP_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG_PP_AC_IMP_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.
**  TRY.
**      GO_AGG->ADD_AGGREGATION( 'PP_SG_PP_AC_PRC_ACUM' ).
**    CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR CX_SALV_EXISTING.
**  ENDTRY.

**--- recibo el objeto layout con el método get_layout del objeto tabla GT_TABLE_ALV
**--- obteniendo una estructura de clave key escrita en slv_s_layout_key, el cual
**--- se guarda y configura en el paso siguiente antes de imprimir el alv
*  GO_LAYOUT = GT_TABLE_ALV->GET_LAYOUT( ).
*
**--- asigno este reporte a la estructura llave (key), variable (Report)
*  GO_KEY-REPORT = SY-REPID.
**--- llamo el método para setear la llave del objeto go_layout con el parámetro go_key
*  GO_LAYOUT->SET_KEY( GO_KEY ).
**--- configuro la restricción de guardado con el método set_save_restriction
*  GO_LAYOUT->SET_SAVE_RESTRICTION( CL_SALV_LAYOUT=>RESTRICT_NONE ).
**--- paso al ALV el parámetro layout escogido por entrada para inicializarlo
*  GO_LAYOUT->SET_INITIAL_LAYOUT( P_LAYOUT ).

  GO_EVENTS = GT_TABLE_ALV->GET_EVENT( ).

  CREATE OBJECT GCL_EVENT_HANDLER.
  SET HANDLER GCL_EVENT_HANDLER->ON_ADDED_FUNCTION FOR GO_EVENTS.

  SET HANDLER GCL_EVENT_HANDLER->ON_LINK_CLICK FOR GO_EVENTS.

**--- Event handler para hacer la columna cantidad editable
*  SET HANDLER GCL_HANDLE_EVENTS=>ON_AFTER_REFRESH
*    FOR ALL INSTANCES
*    ACTIVATION 'X'.

  GT_TABLE_ALV->DISPLAY( ).

ENDFORM.
