*&---------------------------------------------------------------------*
*& Include          ZMMR053_F2
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form F_DSP_RPT
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM F_DSP_RPT.

  DATA: LC_MSG TYPE REF TO CX_SALV_MSG.

  TRY.
      CL_SALV_TABLE=>FACTORY(
        IMPORTING
          R_SALV_TABLE = GT_TABLE_ALV
        CHANGING
          T_TABLE      = GT_OUT ).

    CATCH CX_SALV_MSG INTO LC_MSG.
  ENDTRY.

  GO_FUNCTIONS = GT_TABLE_ALV->GET_FUNCTIONS( ).
  GO_FUNCTIONS->SET_ALL( ABAP_TRUE ).

  GT_TABLE_ALV->SET_SCREEN_STATUS(
    PFSTATUS      = 'ZMM_ST_MMR053'
    REPORT        = SY-REPID
    SET_FUNCTIONS = GT_TABLE_ALV->C_FUNCTIONS_ALL ).

  GO_DSP_SET = GT_TABLE_ALV->GET_DISPLAY_SETTINGS( ).

*--- Zebrado (Striped Pattern)
  CALL METHOD GO_DSP_SET->SET_STRIPED_PATTERN
    EXPORTING
      VALUE = 'X'.

  GO_DSP_SET->SET_LIST_HEADER( 'Reporte de ventas' ).

* CREATE OBJECT GO_HEADER.

**--- Sociedad
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 1 COLUMN = 1 ).
*  GO_H_LABEL->SET_TEXT( '' ).
*  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 1 COLUMN = 2 ).
*  GO_H_LABEL->SET_TEXT(  ).

*  GT_TABLE_ALV->SET_TOP_OF_LIST( GO_HEADER ).
*  GT_TABLE_ALV->SET_TOP_OF_LIST_PRINT( GO_HEADER ).

  GO_SELECTIONS = GT_TABLE_ALV->GET_SELECTIONS( ).
  GO_SELECTIONS->SET_SELECTION_MODE(
    IF_SALV_C_SELECTION_MODE=>ROW_COLUMN ).

  GO_COLUMNS = GT_TABLE_ALV->GET_COLUMNS( ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'CHECK' ).
    CATCH CX_SALV_NOT_FOUND.
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'CHECK' POSITION = '1' ).
  GO_COLUMN->SET_SHORT_TEXT( 'Chk' ).
  GO_COLUMN->SET_MEDIUM_TEXT( 'Chk' ).
  GO_COLUMN->SET_LONG_TEXT( 'Check' ).
  GO_COLUMN->SET_CELL_TYPE( 1 ).
  GO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>CHECKBOX_HOTSPOT ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'EBELN' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'EBELN' POSITION = '2' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( '' ).
  GO_COLUMN->SET_MEDIUM_TEXT( '' ).
  GO_COLUMN->SET_LONG_TEXT( 'Documento de Compras' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'VKORG' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'VKORG' POSITION = '3' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( 'Org. Vtas' ).
  GO_COLUMN->SET_MEDIUM_TEXT( '' ).
  GO_COLUMN->SET_LONG_TEXT( 'Org. Ventas' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'WERKS' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'WERKS' POSITION = '4' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( 'Centro' ).
  GO_COLUMN->SET_MEDIUM_TEXT( 'Centro' ).
  GO_COLUMN->SET_LONG_TEXT( 'Centro' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'ERDAT' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'ERDAT' POSITION = '5' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( 'Fecha' ).
  GO_COLUMN->SET_MEDIUM_TEXT( 'Fecha' ).
  GO_COLUMN->SET_LONG_TEXT( 'Fecha' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'MATNR' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'MATNR' POSITION = '6' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( 'Material' ).
  GO_COLUMN->SET_MEDIUM_TEXT( 'Material' ).
  GO_COLUMN->SET_LONG_TEXT( 'Material' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'FKIMG' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'FKIMG' POSITION = '7' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( '' ).
  GO_COLUMN->SET_MEDIUM_TEXT( '' ).
  GO_COLUMN->SET_LONG_TEXT( 'Cantidad' ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'VRKME' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.
  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMNS->SET_COLUMN_POSITION( COLUMNNAME = 'VRKME' POSITION = '8' ).
  GO_COLUMN->SET_VISIBLE( ABAP_TRUE ).
  GO_COLUMN->SET_SHORT_TEXT( 'UN' ).
  GO_COLUMN->SET_MEDIUM_TEXT( 'Unidad' ).
  GO_COLUMN->SET_LONG_TEXT( 'Unidad' ).

  GO_EVENTS = GT_TABLE_ALV->GET_EVENT( ).

  CREATE OBJECT GCL_EVENT_HANDLER.
  SET HANDLER GCL_EVENT_HANDLER->ON_ADDED_FUNCTION FOR GO_EVENTS.
  SET HANDLER GCL_EVENT_HANDLER->M_LINK_CLICK      FOR GO_EVENTS.

  GT_TABLE_ALV->DISPLAY( ).

ENDFORM.
*&---------------------------------------------------------------------*
*& Form F_OUT_ALV_LOG
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM F_OUT_ALV_LOG.

  DATA: LV_MSG TYPE REF TO CX_SALV_MSG.

  TRY.
      CL_SALV_TABLE=>FACTORY(
        IMPORTING
          R_SALV_TABLE = GT_TABLE_ALV_LOG
        CHANGING
          T_TABLE      = GT_LOG ).
    CATCH CX_SALV_MSG INTO LV_MSG.
  ENDTRY.

  GO_FUNCTIONS = GT_TABLE_ALV_LOG->GET_FUNCTIONS( ).
  GO_FUNCTIONS->SET_ALL( ABAP_TRUE ).

  GO_DSP_SET = GT_TABLE_ALV_LOG->GET_DISPLAY_SETTINGS( ).

*--- Zebrado (Striped Pattern)
  CALL METHOD GO_DSP_SET->SET_STRIPED_PATTERN
    EXPORTING
      VALUE = 'X'.

  GO_DSP_SET->SET_LIST_HEADER('Log reporte tiempo en aire').

*  CREATE OBJECT GO_HEADER.
*
**  GO_H_LABEL = GO_HEADER->CREATE_LABEL( ROW = 2 COLUMN = 1 ).
**  GO_H_LABEL->SET_TEXT( 'Log reporte tiempo en aire' ).
*
*  GT_TABLE_ALV->SET_TOP_OF_LIST( GO_HEADER ).
*  GT_TABLE_ALV->SET_TOP_OF_LIST_PRINT( GO_HEADER ).

  GO_SELECTIONS = GT_TABLE_ALV_LOG->GET_SELECTIONS( ).
  GO_SELECTIONS->SET_SELECTION_MODE(
                     IF_SALV_C_SELECTION_MODE=>ROW_COLUMN ).

  GO_COLUMNS = GT_TABLE_ALV_LOG->GET_COLUMNS( ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'LIGHT' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.

  TRY.
      GO_COLUMNS->SET_EXCEPTION_COLUMN( VALUE = 'LIGHT' ).
    CATCH CX_SALV_DATA_ERROR.
  ENDTRY.

  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMN->SET_SHORT_TEXT( '' ).
  GO_COLUMN->SET_MEDIUM_TEXT( '' ).
  GO_COLUMN->SET_LONG_TEXT( 'Status' ).

  GO_COLUMNS = GT_TABLE_ALV_LOG->GET_COLUMNS( ).

  TRY.
      GO_COLUMN ?= GO_COLUMNS->GET_COLUMN( 'MSG' ).
    CATCH CX_SALV_NOT_FOUND .
  ENDTRY.

  GO_COLUMNS->SET_OPTIMIZE( 'X' ).
  GO_COLUMN->SET_SHORT_TEXT( '' ).
  GO_COLUMN->SET_MEDIUM_TEXT( '' ).
  GO_COLUMN->SET_LONG_TEXT( 'Mensaje retorno tiempo en aire' ).

  GO_LAYOUT = GT_TABLE_ALV_LOG->GET_LAYOUT( ).

  GO_KEY-REPORT = SY-REPID.
  GO_LAYOUT->SET_KEY( GO_KEY ).
  GO_LAYOUT->SET_SAVE_RESTRICTION( CL_SALV_LAYOUT=>RESTRICT_NONE ).

*--- caracteristicas de popup
  GT_TABLE_ALV_LOG->SET_SCREEN_POPUP(
    START_COLUMN = 30
    END_COLUMN = 85
    START_LINE = 1
    END_LINE = 10 ).

  GT_TABLE_ALV_LOG->DISPLAY( ).

ENDFORM.
